/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AssigneeCaptainInput = IDL.Record({
  'assignee' : IDL.Text,
  'captain' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BulkTaskUpdateInput = IDL.Record({
  'updates' : IDL.Vec(
    IDL.Record({
      'status' : IDL.Opt(IDL.Text),
      'paymentStatus' : IDL.Opt(IDL.Text),
      'taskId' : IDL.Text,
    })
  ),
});
export const PaymentStatus = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const TaskCategory = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const SubCategory = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'category' : TaskCategory,
});
export const Time = IDL.Int;
export const Task = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'client' : IDL.Text,
  'subCategory' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'completionDate' : Time,
  'captainName' : IDL.Text,
  'assignmentDate' : Time,
  'owner' : IDL.Principal,
  'bill' : IDL.Nat,
  'advanceReceived' : IDL.Nat,
  'createdAt' : Time,
  'assigneeName' : IDL.Text,
  'dueDate' : Time,
  'comment' : IDL.Text,
  'updatedAt' : Time,
  'outstandingAmount' : IDL.Nat,
  'taskCategory' : IDL.Text,
});
export const TaskStatus = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
});
export const AssigneeCaptainUpdate = IDL.Record({
  'assignee' : IDL.Text,
  'captain' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAssigneeCaptainPair' : IDL.Func([AssigneeCaptainInput], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkDeleteAssigneeCaptainPairs' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'bulkDeleteTasks' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'bulkUpdateAssigneeCaptainPairs' : IDL.Func(
      [IDL.Vec(AssigneeCaptainInput)],
      [],
      [],
    ),
  'bulkUpdateTasks' : IDL.Func([BulkTaskUpdateInput], [], []),
  'createPaymentStatus' : IDL.Func([IDL.Text], [PaymentStatus], []),
  'createSubCategory' : IDL.Func([IDL.Text, TaskCategory], [SubCategory], []),
  'createTask' : IDL.Func(
      [
        IDL.Opt(IDL.Principal),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Time,
        Time,
        Time,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [Task],
      [],
    ),
  'createTaskCategory' : IDL.Func([IDL.Text], [TaskCategory], []),
  'createTaskStatus' : IDL.Func([IDL.Text], [TaskStatus], []),
  'deleteAssigneeCaptainPair' : IDL.Func([IDL.Text], [], []),
  'getAssigneeCaptainDirectory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPaymentStatuses' : IDL.Func([], [IDL.Vec(PaymentStatus)], ['query']),
  'getSubCategories' : IDL.Func([], [IDL.Vec(SubCategory)], ['query']),
  'getTask' : IDL.Func([IDL.Text], [IDL.Opt(Task)], ['query']),
  'getTaskCategories' : IDL.Func([], [IDL.Vec(TaskCategory)], ['query']),
  'getTaskStatuses' : IDL.Func([], [IDL.Vec(TaskStatus)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAssigneeCaptainPair' : IDL.Func(
      [IDL.Text, AssigneeCaptainUpdate],
      [],
      [],
    ),
  'updateTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Time,
        Time,
        Time,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [Task],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AssigneeCaptainInput = IDL.Record({
    'assignee' : IDL.Text,
    'captain' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BulkTaskUpdateInput = IDL.Record({
    'updates' : IDL.Vec(
      IDL.Record({
        'status' : IDL.Opt(IDL.Text),
        'paymentStatus' : IDL.Opt(IDL.Text),
        'taskId' : IDL.Text,
      })
    ),
  });
  const PaymentStatus = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const TaskCategory = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const SubCategory = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'category' : TaskCategory,
  });
  const Time = IDL.Int;
  const Task = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'client' : IDL.Text,
    'subCategory' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'completionDate' : Time,
    'captainName' : IDL.Text,
    'assignmentDate' : Time,
    'owner' : IDL.Principal,
    'bill' : IDL.Nat,
    'advanceReceived' : IDL.Nat,
    'createdAt' : Time,
    'assigneeName' : IDL.Text,
    'dueDate' : Time,
    'comment' : IDL.Text,
    'updatedAt' : Time,
    'outstandingAmount' : IDL.Nat,
    'taskCategory' : IDL.Text,
  });
  const TaskStatus = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
  });
  const AssigneeCaptainUpdate = IDL.Record({
    'assignee' : IDL.Text,
    'captain' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAssigneeCaptainPair' : IDL.Func([AssigneeCaptainInput], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkDeleteAssigneeCaptainPairs' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'bulkDeleteTasks' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'bulkUpdateAssigneeCaptainPairs' : IDL.Func(
        [IDL.Vec(AssigneeCaptainInput)],
        [],
        [],
      ),
    'bulkUpdateTasks' : IDL.Func([BulkTaskUpdateInput], [], []),
    'createPaymentStatus' : IDL.Func([IDL.Text], [PaymentStatus], []),
    'createSubCategory' : IDL.Func([IDL.Text, TaskCategory], [SubCategory], []),
    'createTask' : IDL.Func(
        [
          IDL.Opt(IDL.Principal),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Time,
          Time,
          Time,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [Task],
        [],
      ),
    'createTaskCategory' : IDL.Func([IDL.Text], [TaskCategory], []),
    'createTaskStatus' : IDL.Func([IDL.Text], [TaskStatus], []),
    'deleteAssigneeCaptainPair' : IDL.Func([IDL.Text], [], []),
    'getAssigneeCaptainDirectory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPaymentStatuses' : IDL.Func([], [IDL.Vec(PaymentStatus)], ['query']),
    'getSubCategories' : IDL.Func([], [IDL.Vec(SubCategory)], ['query']),
    'getTask' : IDL.Func([IDL.Text], [IDL.Opt(Task)], ['query']),
    'getTaskCategories' : IDL.Func([], [IDL.Vec(TaskCategory)], ['query']),
    'getTaskStatuses' : IDL.Func([], [IDL.Vec(TaskStatus)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAssigneeCaptainPair' : IDL.Func(
        [IDL.Text, AssigneeCaptainUpdate],
        [],
        [],
      ),
    'updateTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Time,
          Time,
          Time,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [Task],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };