/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssigneeCaptainInput {
  'assignee' : string,
  'captain' : string,
}
export interface AssigneeCaptainUpdate {
  'assignee' : string,
  'captain' : string,
}
export interface PaymentStatus { 'id' : string, 'name' : string }
export interface SubCategory {
  'id' : string,
  'name' : string,
  'category' : TaskCategory,
}
export interface Task {
  'id' : string,
  'status' : string,
  'client' : string,
  'subCategory' : string,
  'paymentStatus' : string,
  'captainName' : string,
  'owner' : Principal,
  'createdAt' : Time,
  'assigneeName' : string,
  'updatedAt' : Time,
  'taskCategory' : string,
}
export interface TaskCategory { 'id' : string, 'name' : string }
export interface TaskStatus { 'id' : string, 'name' : string }
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'createdAt' : Time,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAssigneeCaptainPair' : ActorMethod<[AssigneeCaptainInput], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkCreateTasks' : ActorMethod<
    [
      Array<
        [Principal, string, string, string, string, string, string, string]
      >,
    ],
    Array<Task>
  >,
  'bulkUpdateAssigneeCaptainPairs' : ActorMethod<
    [Array<AssigneeCaptainInput>],
    undefined
  >,
  'createPaymentStatus' : ActorMethod<[string], PaymentStatus>,
  'createSubCategory' : ActorMethod<[string, TaskCategory], SubCategory>,
  'createTask' : ActorMethod<
    [[] | [Principal], string, string, string, string, string, string, string],
    Task
  >,
  'createTaskCategory' : ActorMethod<[string], TaskCategory>,
  'createTaskStatus' : ActorMethod<[string], TaskStatus>,
  'createUser' : ActorMethod<[Principal, string, string], UserProfile>,
  'deleteAssigneeCaptainPair' : ActorMethod<[string], undefined>,
  'deleteTask' : ActorMethod<[string], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'filterTasksByAssigneeName' : ActorMethod<[string], Array<Task>>,
  'filterTasksByCaptainName' : ActorMethod<[string], Array<Task>>,
  'filterTasksByCategory' : ActorMethod<[string], Array<Task>>,
  'filterTasksByClient' : ActorMethod<[string], Array<Task>>,
  'filterTasksByPaymentStatus' : ActorMethod<[string], Array<Task>>,
  'filterTasksByStatus' : ActorMethod<[string], Array<Task>>,
  'filterTasksBySubCategory' : ActorMethod<[string], Array<Task>>,
  'getAssigneeCaptainDirectory' : ActorMethod<[], Array<[string, string]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPaymentStatuses' : ActorMethod<[], Array<PaymentStatus>>,
  'getSubCategories' : ActorMethod<[], Array<SubCategory>>,
  'getTask' : ActorMethod<[string], [] | [Task]>,
  'getTaskCategories' : ActorMethod<[], Array<TaskCategory>>,
  'getTaskCountsPerCategory' : ActorMethod<[], Array<[string, bigint]>>,
  'getTaskCountsPerPaymentStatus' : ActorMethod<[], Array<[string, bigint]>>,
  'getTaskCountsPerStatus' : ActorMethod<[], Array<[string, bigint]>>,
  'getTaskStatuses' : ActorMethod<[], Array<TaskStatus>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[Principal], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'updateAssigneeCaptainPair' : ActorMethod<
    [string, AssigneeCaptainUpdate],
    undefined
  >,
  'updateTask' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    Task
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];