/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssigneeCaptainInput {
  'assignee' : string,
  'captain' : string,
}
export interface AssigneeCaptainUpdate {
  'assignee' : string,
  'captain' : string,
}
export interface BulkTaskUpdateInput {
  'updates' : Array<
    {
      'status' : [] | [string],
      'paymentStatus' : [] | [string],
      'taskId' : string,
    }
  >,
}
export interface PaymentStatus { 'id' : string, 'name' : string }
export interface SubCategory {
  'id' : string,
  'name' : string,
  'category' : TaskCategory,
}
export interface Task {
  'id' : string,
  'status' : string,
  'client' : string,
  'subCategory' : string,
  'paymentStatus' : string,
  'completionDate' : Time,
  'captainName' : string,
  'assignmentDate' : Time,
  'owner' : Principal,
  'bill' : bigint,
  'advanceReceived' : bigint,
  'createdAt' : Time,
  'assigneeName' : string,
  'dueDate' : Time,
  'comment' : string,
  'updatedAt' : Time,
  'outstandingAmount' : bigint,
  'taskCategory' : string,
}
export interface TaskCategory { 'id' : string, 'name' : string }
export interface TaskStatus { 'id' : string, 'name' : string }
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'createdAt' : Time,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAssigneeCaptainPair' : ActorMethod<[AssigneeCaptainInput], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkDeleteAssigneeCaptainPairs' : ActorMethod<[Array<string>], undefined>,
  'bulkDeleteTasks' : ActorMethod<[Array<string>], undefined>,
  'bulkUpdateAssigneeCaptainPairs' : ActorMethod<
    [Array<AssigneeCaptainInput>],
    undefined
  >,
  'bulkUpdateTasks' : ActorMethod<[BulkTaskUpdateInput], undefined>,
  'createPaymentStatus' : ActorMethod<[string], PaymentStatus>,
  'createSubCategory' : ActorMethod<[string, TaskCategory], SubCategory>,
  'createTask' : ActorMethod<
    [
      [] | [Principal],
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      Time,
      Time,
      Time,
      bigint,
      bigint,
      bigint,
    ],
    Task
  >,
  'createTaskCategory' : ActorMethod<[string], TaskCategory>,
  'createTaskStatus' : ActorMethod<[string], TaskStatus>,
  'deleteAssigneeCaptainPair' : ActorMethod<[string], undefined>,
  'getAssigneeCaptainDirectory' : ActorMethod<[], Array<[string, string]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPaymentStatuses' : ActorMethod<[], Array<PaymentStatus>>,
  'getSubCategories' : ActorMethod<[], Array<SubCategory>>,
  'getTask' : ActorMethod<[string], [] | [Task]>,
  'getTaskCategories' : ActorMethod<[], Array<TaskCategory>>,
  'getTaskStatuses' : ActorMethod<[], Array<TaskStatus>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAssigneeCaptainPair' : ActorMethod<
    [string, AssigneeCaptainUpdate],
    undefined
  >,
  'updateTask' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      Time,
      Time,
      Time,
      bigint,
      bigint,
      bigint,
    ],
    Task
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];